// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TestDependentTypes")>]
[<assembly: AssemblyProductAttribute("TestDependentTypes")>]
[<assembly: AssemblyDescriptionAttribute("Personal Server")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TestDependentTypes"
    let [<Literal>] AssemblyProduct = "TestDependentTypes"
    let [<Literal>] AssemblyDescription = "Personal Server"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
